version: "3.8"
services:
  ip:
    container_name: ip
    image: gfsolone/ip:latest
    ports:
      - "80:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    environment:
      ENABLE_DEBUG: "false"
      DEBUG_TOKEN: "your_super_secret_token_here"
    restart: unless-stopped
